ALTER TABLE chain_steps ADD COLUMN input_per_m DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE chain_steps ADD COLUMN output_per_m DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE chain_steps ADD COLUMN cache_write_per_m DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE chain_steps ADD COLUMN cache_read_per_m DOUBLE PRECISION NOT NULL DEFAULT 0;