import { Bug, Sparkles, Gauge, BookOpen, Wrench, Package, Circle } from "lucide-react";

// ── Types ────────────────────────────────────────────────────────────
interface ChangelogEntry {
  scope: string;
  description: string;
  commit?: string;
}

interface ChangelogSection {
  category: string;
  entries: ChangelogEntry[];
}

interface ChangelogRelease {
  version: string;
  date: string;
  sections: ChangelogSection[];
}

// ── Category metadata ────────────────────────────────────────────────
// Category icons are quiet glyphs; the label carries the meaning.
const categoryMeta: Record<string, { icon: typeof Bug; label: string }> = {
  "bug fixes": { icon: Bug, label: "Bug fixes" },
  features: { icon: Sparkles, label: "Features" },
  performance: { icon: Gauge, label: "Performance" },
  documentation: { icon: BookOpen, label: "Documentation" },
  ci: { icon: Wrench, label: "CI" },
  refactor: { icon: Package, label: "Refactor" },
};

function getCategoryMeta(category: string) {
  const key = category.toLowerCase();
  return categoryMeta[key] ?? { icon: Circle, label: category };
}

// ── Inline markdown ──────────────────────────────────────────────────
// Renders `code`, **bold** and [text](https://…) inside an entry as React
// nodes (never raw HTML). Anything else stays plain text.
const INLINE_RE = /(`[^`]+`|\*\*[^*]+\*\*|\[[^\]]+\]\(https?:\/\/[^\s)]+\))/g;

function InlineMarkdown({ text }: { text: string }) {
  const parts = text.split(INLINE_RE);
  return (
    <>
      {parts.map((part, i) => {
        if (!part) return null;
        if (part.startsWith("`") && part.endsWith("`") && part.length > 2) {
          return (
            <code key={i} className="rounded-md bg-subtle px-1 py-px font-mono text-[12px] text-fg">
              {part.slice(1, -1)}
            </code>
          );
        }
        if (part.startsWith("**") && part.endsWith("**") && part.length > 4) {
          return <strong key={i} className="font-semibold text-fg">{part.slice(2, -2)}</strong>;
        }
        const link = part.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/);
        if (link) {
          return (
            <a
              key={i}
              href={link[2]}
              target="_blank"
              rel="noreferrer noopener"
              className="text-link hover:underline"
            >
              {link[1]}
              <span className="sr-only"> (opens in a new tab)</span>
            </a>
          );
        }
        return <span key={i}>{part}</span>;
      })}
    </>
  );
}

// ── Parser ───────────────────────────────────────────────────────────
function parseChangelog(raw: string): ChangelogRelease[] {
  if (!raw) return [];

  // Strip HTML comments (e.g. <!-- generated by git-cliff -->)
  const cleaned = raw.replace(/<!--[\s\S]*?-->/g, "").trim();
  const lines = cleaned.split("\n");
  const releases: ChangelogRelease[] = [];

  let current: ChangelogRelease | null = null;
  let currentSection: ChangelogSection | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Skip the top-level "# Changelog" header
    if (/^#\s+Changelog/i.test(trimmed)) continue;

    // ## [version] — date  OR  ## version — date
    const versionMatch = trimmed.match(
      /^##\s+\[?v?([\d.]+)\]?\s*(?:—|--|–|-)\s*(.*)/
    );
    if (versionMatch) {
      current = {
        version: versionMatch[1],
        date: versionMatch[2].trim(),
        sections: [],
      };
      releases.push(current);
      currentSection = null;
      continue;
    }

    // ### Category
    const catMatch = trimmed.match(/^###\s+(.+)/);
    if (catMatch && current) {
      currentSection = { category: catMatch[1].trim(), entries: [] };
      current.sections.push(currentSection);
      continue;
    }

    // - **scope:** description(hash)  OR  - description(hash)
    const itemMatch = trimmed.match(
      /^[-*]\s+(?:\*\*(.+?):\*\*\s*)?(.+?)(?:\(([a-f0-9]{7,})\))?$/
    );
    if (itemMatch && currentSection) {
      currentSection.entries.push({
        scope: itemMatch[1] || "",
        description: itemMatch[2].trim(),
        commit: itemMatch[3],
      });
      continue;
    }

    // Fallback: any other "- text" line
    const fallbackMatch = trimmed.match(/^[-*]\s+(.+)/);
    if (fallbackMatch && currentSection) {
      currentSection.entries.push({
        scope: "",
        description: fallbackMatch[1].trim(),
      });
    }
  }

  return releases;
}

// ── Component ────────────────────────────────────────────────────────
export function ChangelogMarkdown({
  changelog,
  compact = false,
  headingLevel = 3,
}: {
  changelog: string;
  compact?: boolean;
  /** Level of the per-release heading (category headings are one below). Default 3. */
  headingLevel?: 2 | 3 | 4;
}) {
  const releases = parseChangelog(changelog);
  const ReleaseHeading = `h${headingLevel}` as "h2" | "h3" | "h4";
  const CategoryHeading = `h${headingLevel + 1}` as "h3" | "h4" | "h5";

  if (releases.length === 0) {
    // Fallback: render as plain text if parser found nothing
    return (
      <p className="whitespace-pre-wrap text-[13px] leading-5 text-fg">
        {changelog}
      </p>
    );
  }

  return (
    <div className={compact ? "space-y-4 text-fg" : "space-y-6 text-fg"}>
      {releases.map((rel, releaseIndex) => (
        <section key={rel.version} className={releaseIndex > 0 ? "border-t border-line pt-4" : undefined}>
          {/* Version header */}
          <div className="mb-2.5 flex min-w-0 items-baseline gap-2">
            <ReleaseHeading className="shrink-0 font-mono text-[13px] font-semibold text-fg">v{rel.version}</ReleaseHeading>
            {rel.date && (
              <span className="min-w-0 truncate text-[12px] tabular-nums text-fg-muted">{rel.date}</span>
            )}
          </div>

          {/* Sections */}
          {rel.sections.length > 0 ? (
            <div className={compact ? "space-y-3" : "space-y-4"}>
              {rel.sections.map((sec) => {
                const meta = getCategoryMeta(sec.category);
                const Icon = meta.icon;
                return (
                  <div key={sec.category}>
                    <CategoryHeading className="mb-1 flex items-center gap-1.5 text-[12.5px] font-semibold text-fg">
                      <Icon className="h-3.5 w-3.5 text-fg-faint" strokeWidth={1.75} aria-hidden="true" />
                      {meta.label}
                    </CategoryHeading>
                    <ul className="space-y-1">
                      {sec.entries.map((entry, i) => (
                        <li
                          key={i}
                          className="flex min-w-0 items-start gap-2 text-[13px] leading-5 text-fg"
                        >
                          <span className="mt-[9px] h-1 w-1 shrink-0 rounded-full bg-fg-faint" aria-hidden="true" />
                          <span className="min-w-0 break-words">
                            {entry.scope && (
                              <span className="mr-1.5 inline-flex items-center rounded-md bg-subtle px-1 py-px font-mono text-[11.5px] text-fg-muted">
                                {entry.scope}
                              </span>
                            )}
                            <InlineMarkdown text={entry.description} />
                            {entry.commit && (
                              <span className="ml-1.5 whitespace-nowrap font-mono text-[11.5px] text-fg-faint">
                                <span className="sr-only">commit </span>
                                {entry.commit}
                              </span>
                            )}
                          </span>
                        </li>
                      ))}
                    </ul>
                  </div>
                );
              })}
            </div>
          ) : (
            <p className="text-[13px] text-fg-muted">No detailed changes listed.</p>
          )}
        </section>
      ))}
    </div>
  );
}
