// One icon per concept, everywhere. Pages import from here instead of picking
// a lucide glyph ad hoc, so "requests" or "latency" look the same on Overview,
// Usage, Health, Keys and the portal. Sizes: 16px (h-4 w-4), strokeWidth 1.75.
import {
  Activity,
  AlertTriangle,
  ArrowRightLeft,
  BarChart3,
  Boxes,
  Brain,
  Clock,
  Coins,
  Cpu,
  Database,
  DollarSign,
  Gauge,
  GitBranch,
  Globe,
  HardDrive,
  Image,
  Key,
  Layers,
  LayoutGrid,
  ListChecks,
  MemoryStick,
  MessageSquare,
  Network,
  PiggyBank,
  Plug,
  ReceiptText,
  ScrollText,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  TerminalSquare,
  Timer,
  TrendingUp,
  Users,
  Waypoints,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  // Sections (match the sidebar)
  overview: LayoutGrid,
  usage: BarChart3,
  console: ScrollText,
  endpoints: Plug,
  chains: Layers,
  skills: Sparkles,
  providers: Boxes,
  media: Image,
  health: Activity,
  quota: Gauge,
  proxyPools: Waypoints,
  keys: Key,
  plans: ReceiptText,
  guardrails: Shield,
  cliTools: TerminalSquare,
  system: Cpu,
  settings: Settings,

  // Metrics
  requests: Zap,
  successRate: ShieldCheck,
  errors: AlertTriangle,
  latency: Timer,
  tokens: Coins,
  spend: DollarSign,
  savings: PiggyBank,
  budget: Wallet,
  trend: TrendingUp,
  fallbacks: ArrowRightLeft,
  uptime: Clock,

  // Things
  model: Brain,
  account: Users,
  route: GitBranch,
  network: Network,
  tunnel: Globe,
  server: Server,
  database: Database,
  disk: HardDrive,
  memory: MemoryStick,
  prompt: MessageSquare,
  checklist: ListChecks,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
